In [1]:
import numpy as np

# Input image (4x4)
img = np.array([[1,2,3,0],
                [0,1,2,3],
                [3,0,1,2],
                [2,3,0,1]])

# Kernel (2x2)
kernel = np.array([[1,-1],
                   [1,-1]])

# 1) Convolution (valid, stride=1)
conv = np.zeros((3,3), dtype=int)
for i in range(3):
    for j in range(3):
        patch = img[i:i+2, j:j+2]
        conv[i,j] = np.sum(patch * kernel)

# 2) ReLU
relu = np.maximum(conv, 0)

# 3) Max Pooling (2x2, stride=1)
pooled = np.zeros((2,2), dtype=int)
for i in range(2):
    for j in range(2):
        pooled[i,j] = np.max(relu[i:i+2, j:j+2])

# 4) Flatten
flat = pooled.flatten()   # shape (4,)

# 5) Fully connected (2 outputs)
W = np.array([[1.0, -1.0, 1.0, 0.0],
              [0.5,  0.5, -0.5, 1.0]])
b = np.array([0.0, 0.0])

z = W.dot(flat) + b

# 6) Softmax
def softmax(x):
    ex = np.exp(x - np.max(x))
    return ex / np.sum(ex)

probs = softmax(z)

print("Image:\n", img)
print("Kernel:\n", kernel)
print("Conv:\n", conv)
print("ReLU:\n", relu)
print("Pooled:\n", pooled)
print("Flatten:", flat)
print("FC pre-activation z:", z)
print("Softmax probabilities:", probs)


Image:
 [[1 2 3 0]
 [0 1 2 3]
 [3 0 1 2]
 [2 3 0 1]]
Kernel:
 [[ 1 -1]
 [ 1 -1]]
Conv:
 [[-2 -2  2]
 [ 2 -2 -2]
 [ 2  2 -2]]
ReLU:
 [[0 0 2]
 [2 0 0]
 [2 2 0]]
Pooled:
 [[2 2]
 [2 2]]
Flatten: [2 2 2 2]
FC pre-activation z: [2. 3.]
Softmax probabilities: [0.26894142 0.73105858]
